[package]
name = "joshephus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "joshephus"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "lib_bench"
harness = false
